export type Styles = {
  "active": string;
  "backgroundPattern": string;
  "bold109": string;
  "bold150": string;
  "bold178": string;
  "bold24": string;
  "bold32": string;
  "bold41": string;
  "bold60": string;
  "bold67": string;
  "bold90": string;
  "boldDesktop25Mobile9": string;
  "boldDesktop41Mobile25": string;
  "container": string;
  "content3": string;
  "contentContainer": string;
  "extraBold67": string;
  "extraBold90": string;
  "extraBoldDesktop65Mobile28": string;
  "fullbold109": string;
  "fullBold67": string;
  "headerEmphasisText": string;
  "hide": string;
  "highlightText": string;
  "medium25": string;
  "panel": string;
  "panelHeader": string;
  "parallaxColumnRigth": string;
  "regular14": string;
  "regular16": string;
  "regular20": string;
  "regular24": string;
  "regular25": string;
  "regular32": string;
  "regular90": string;
  "regularDesktop16Mobile7": string;
  "regularDesktop20Mobile7": string;
  "regularDesktop25Mobile16": string;
  "regularDesktop25Mobile9": string;
  "regularDesktop30Mobile20": string;
  "selector": string;
  "selectors": string;
  "semiBold90": string;
  "show": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
