export type Styles = {
  "accordianBody": string;
  "accordianHeader": string;
  "accordion": string;
  "active": string;
  "activeTab": string;
  "backgroundPattern": string;
  "bold109": string;
  "bold150": string;
  "bold178": string;
  "bold24": string;
  "bold25": string;
  "bold32": string;
  "bold41": string;
  "bold60": string;
  "bold67": string;
  "bold90": string;
  "boldDesktop41Mobile25": string;
  "card": string;
  "content": string;
  "contentContainer": string;
  "contentHeading": string;
  "customAccordianButton": string;
  "dirtyWhite": string;
  "extraBold41": string;
  "extraBold67": string;
  "extraBold90": string;
  "extraBoldDesktop65Mobile28": string;
  "faqIndex": string;
  "fullbold109": string;
  "fullBold67": string;
  "inactive": string;
  "regular14": string;
  "regular16": string;
  "regular24": string;
  "regular25": string;
  "regular32": string;
  "regular90": string;
  "regularDesktop25Mobile16": string;
  "regularDesktop25Mobile9": string;
  "semiBold32": string;
  "semiBold90": string;
  "tab": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
