export type Styles = {
  "animationGrid": string;
  "avatarHeading": string;
  "avatarInner": string;
  "avatarWrapper": string;
  "backgroundPattern": string;
  "bold109": string;
  "bold150": string;
  "bold178": string;
  "bold24": string;
  "bold32": string;
  "bold41": string;
  "bold60": string;
  "bold67": string;
  "bold90": string;
  "coin": string;
  "container": string;
  "contentAnimation": string;
  "contentShow": string;
  "contetHide": string;
  "donationActive": string;
  "donationCycleItems": string;
  "donationInner": string;
  "donations": string;
  "example": string;
  "extraBold90": string;
  "fadeIn": string;
  "friends": string;
  "fullBold67": string;
  "gameStepThree": string;
  "gameStepThreeFriendsColumn": string;
  "gameStepThreeUserColumn": string;
  "gameStepTwo": string;
  "hide": string;
  "opacityAnimation": string;
  "percentageFriends": string;
  "percentageSelected": string;
  "regular16": string;
  "regular24": string;
  "regular25": string;
  "regular90": string;
  "regularDesktop25Mobile9": string;
  "selected": string;
  "semiBold90": string;
  "show": string;
  "signUpsection": string;
  "yellow": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
