export type Styles = {
  "animationGrid": string;
  "avatarAnimation": string;
  "avatarHeading": string;
  "avatarInner": string;
  "avatarWrapper": string;
  "backgroundPattern": string;
  "bold109": string;
  "bold150": string;
  "bold178": string;
  "bold24": string;
  "bold32": string;
  "bold41": string;
  "bold60": string;
  "bold67": string;
  "bold90": string;
  "boldGame41": string;
  "boldGame67": string;
  "coin": string;
  "coinAnimatonMobile": string;
  "coinDefault": string;
  "container": string;
  "containerFadIn": string;
  "containerFadinAnimation": string;
  "containerFadOut": string;
  "containerFadoutAnimation": string;
  "contentAnimation": string;
  "contentShow": string;
  "contetHide": string;
  "displayAnimation": string;
  "donationActive": string;
  "donationCycleItems": string;
  "donationDesktop": string;
  "donationInner": string;
  "donationMobile": string;
  "donations": string;
  "example": string;
  "extraBold67": string;
  "extraBold90": string;
  "extraBoldDesktop65Mobile28": string;
  "fadeIn": string;
  "friends": string;
  "fullbold109": string;
  "fullBold67": string;
  "gameStepFive": string;
  "gameStepOne": string;
  "gameStepSix": string;
  "gameStepThree": string;
  "gameStepThreeFriendsColumn": string;
  "gameStepThreeUserColumn": string;
  "gameStepTwo": string;
  "gameStepTwoWrapper": string;
  "medium25": string;
  "opacityAnimation": string;
  "percentageFriends": string;
  "percentageSelected": string;
  "regular16": string;
  "regular20": string;
  "regular24": string;
  "regular25": string;
  "regular32": string;
  "regular90": string;
  "regularDesktop25Mobile16": string;
  "regularDesktop25Mobile9": string;
  "selected": string;
  "semiBold90": string;
  "show": string;
  "signUpsection": string;
  "stepFour": string;
  "user": string;
  "userAvatar": string;
  "userDonation": string;
  "yellow": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
