export type Styles = {
  "avatar": string;
  "avatarFriends": string;
  "avatarHeading": string;
  "avatarSelected": string;
  "backgroundPattern": string;
  "bold109": string;
  "bold150": string;
  "bold178": string;
  "bold24": string;
  "bold32": string;
  "bold41": string;
  "bold60": string;
  "bold67": string;
  "bold90": string;
  "boldDesktop25Mobile9": string;
  "boldDesktop41Mobile25": string;
  "card": string;
  "close": string;
  "extraBold67": string;
  "extraBold90": string;
  "extraBoldDesktop65Mobile28": string;
  "friendsBottom": string;
  "friendsColumn": string;
  "friendsTop": string;
  "fullbold109": string;
  "fullBold67": string;
  "gameStepThree": string;
  "gameStepTwo": string;
  "gameStepTwoWrapper": string;
  "medium25": string;
  "modalBody": string;
  "percentageWrapper": string;
  "regular14": string;
  "regular16": string;
  "regular20": string;
  "regular24": string;
  "regular25": string;
  "regular32": string;
  "regular90": string;
  "regularDesktop16Mobile7": string;
  "regularDesktop20Mobile7": string;
  "regularDesktop25Mobile16": string;
  "regularDesktop25Mobile9": string;
  "regularDesktop30Mobile20": string;
  "semiBold90": string;
  "targetOne": string;
  "targetTwo": string;
  "transparent": string;
  "user": string;
  "userColumn": string;
  "userColumnInner": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
