export type Styles = {
  "active": string;
  "activeTab": string;
  "avatarHeading": string;
  "avatarInner": string;
  "backgroundPattern": string;
  "bold109": string;
  "bold150": string;
  "bold178": string;
  "bold24": string;
  "bold32": string;
  "bold41": string;
  "bold60": string;
  "bold67": string;
  "bold90": string;
  "boldDesktop25Mobile9": string;
  "boldDesktop41Mobile25": string;
  "boldGame41": string;
  "boldGame67": string;
  "confetti": string;
  "confettiRight": string;
  "donationActive": string;
  "donationButton": string;
  "donationDesktop": string;
  "donationInner": string;
  "donationMobile": string;
  "donations": string;
  "extraBold67": string;
  "extraBold90": string;
  "extraBoldDesktop65Mobile28": string;
  "flexOne": string;
  "friendsBottom": string;
  "friendsMain": string;
  "friendsTop": string;
  "fullbold109": string;
  "fullBold67": string;
  "gameStepFive": string;
  "inactive": string;
  "left": string;
  "medium25": string;
  "navToggle": string;
  "percentageFriends": string;
  "percentageSelected": string;
  "regular14": string;
  "regular16": string;
  "regular20": string;
  "regular24": string;
  "regular25": string;
  "regular32": string;
  "regular90": string;
  "regularDesktop20Mobile7": string;
  "regularDesktop25Mobile16": string;
  "regularDesktop25Mobile9": string;
  "regularDesktop30Mobile20": string;
  "right": string;
  "semiBold90": string;
  "yellow": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
