export type Styles = {
  "backgroundPattern": string;
  "bold109": string;
  "bold14": string;
  "bold150": string;
  "bold16": string;
  "bold178": string;
  "bold24": string;
  "bold25": string;
  "bold31": string;
  "bold32": string;
  "bold36": string;
  "bold41": string;
  "bold51": string;
  "bold60": string;
  "bold67": string;
  "bold90": string;
  "boldDesktop41Mobile25": string;
  "buttonFaq": string;
  "container": string;
  "contextContainer": string;
  "countryflagContainer": string;
  "extraBold41": string;
  "extraBold67": string;
  "extraBold90": string;
  "extraBoldDesktop65Mobile28": string;
  "formBottomContent": string;
  "formButtons": string;
  "formContainer": string;
  "formContent": string;
  "formDesc": string;
  "formTitle": string;
  "fullbold109": string;
  "fullBold67": string;
  "inactive": string;
  "inputPhoneNumber": string;
  "medium14": string;
  "medium16": string;
  "note": string;
  "overlay": string;
  "phoneNumberContainer": string;
  "regular12": string;
  "regular14": string;
  "regular16": string;
  "regular18": string;
  "regular24": string;
  "regular25": string;
  "regular32": string;
  "regular90": string;
  "regularDesktop25Mobile16": string;
  "regularDesktop25Mobile9": string;
  "semiBold14": string;
  "semiBold20": string;
  "semiBold25": string;
  "semiBold32": string;
  "semiBold90": string;
  "thankYou": string;
  "title": string;
  "topContextContainer": string;
  "userTypeButton": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
