export type Styles = {
  "backgroundPattern": string;
  "bold109": string;
  "bold150": string;
  "bold178": string;
  "bold24": string;
  "bold32": string;
  "bold41": string;
  "bold60": string;
  "bold67": string;
  "bold90": string;
  "boldGame41": string;
  "boldGame67": string;
  "btnGetStarted": string;
  "content2": string;
  "content2Container": string;
  "extraBold67": string;
  "extraBold90": string;
  "extraBoldDesktop65Mobile28": string;
  "fullbold109": string;
  "fullBold67": string;
  "hide": string;
  "leftSection": string;
  "leftSectionRight": string;
  "medium25": string;
  "regular16": string;
  "regular20": string;
  "regular24": string;
  "regular25": string;
  "regular32": string;
  "regular90": string;
  "regularDesktop25Mobile16": string;
  "regularDesktop25Mobile9": string;
  "regularDesktop30Mobile20": string;
  "resetLeft": string;
  "resetRight": string;
  "rightSection": string;
  "rightSectionLeft": string;
  "semiBold90": string;
  "show": string;
  "showLeft": string;
  "showLeftIn": string;
  "showRight": string;
  "showRightIn": string;
  "wrapperDiv": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
