export type Styles = {
  "arrowContainer": string;
  "backgroundPattern": string;
  "bold109": string;
  "bold14": string;
  "bold150": string;
  "bold16": string;
  "bold178": string;
  "bold24": string;
  "bold25": string;
  "bold31": string;
  "bold32": string;
  "bold36": string;
  "bold41": string;
  "bold51": string;
  "bold60": string;
  "bold67": string;
  "bold90": string;
  "boldDesktop25Mobile24": string;
  "boldDesktop31Mobile20": string;
  "boldDesktop36Mobile24": string;
  "boldDesktop25Mobile9": string;
  "boldDesktop41Mobile25": string;
  "card": string;
  "cardContainer": string;
  "cardContent": string;
  "cardStack": string;
  "container": string;
  "content1": string;
  "extraBold41": string;
  "extraBold67": string;
  "extraBold90": string;
  "extraBoldDesktop65Mobile28": string;
  "fullbold109": string;
  "fullBold67": string;
  "imageContainer": string;
  "imageLogoContainer": string;
  "leftSection": string;
  "medium14": string;
  "medium16": string;
  "regular12": string;
  "regular14": string;
  "regular16": string;
  "regular18": string;
  "medium25": string;
  "regular14": string;
  "regular16": string;
  "regular20": string;
  "regular24": string;
  "regular25": string;
  "regular32": string;
  "regular90": string;
  "regularDesktop16Mobile12": string;
  "regularDesktop16Mobile14": string;
  "regularDesktop16Mobile16": string;
  "regularDesktop16Mobile7": string;
  "regularDesktop20Mobile7": string;
  "regularDesktop25Mobile16": string;
  "regularDesktop25Mobile9": string;
  "regularDesktop30Mobile20": string;
  "rightSection": string;
  "rightSectionContainer": string;
  "sectionContainer": string;
  "semiBold14": string;
  "semiBold20": string;
  "semiBold25": string;
  "semiBold20": string;
  "semiBold32": string;
  "semiBold90": string;
  "semiBoldDesktop16Mobile14": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
